// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/3/8 23:34:56
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/chenyongchang/lib/outsource/hz/ultra_jogging_web/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/chenyongchang/lib/outsource/hz/ultra_jogging_web/src/components//**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/chenyongchang/lib/outsource/hz/ultra_jogging_web/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/chenyongchang/lib/outsource/hz/ultra_jogging_web/src/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/chenyongchang/lib/outsource/hz/ultra_jogging_web/src/plugins/**/*.{js,ts,mjs}","/Users/chenyongchang/lib/outsource/hz/ultra_jogging_web/composables/**/*.{js,ts,mjs}","/Users/chenyongchang/lib/outsource/hz/ultra_jogging_web/utils/**/*.{js,ts,mjs}","/Users/chenyongchang/lib/outsource/hz/ultra_jogging_web/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/chenyongchang/lib/outsource/hz/ultra_jogging_web/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/chenyongchang/lib/outsource/hz/ultra_jogging_web/src/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;